language: node_js

node_js:
  - 0.12

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq netpbm

install:
  - npm install
  - npm install -g cypress

script:
  - http-server -p 6060 &
  - cypress ci
