addons:
  artifacts:
    paths:
     - ./screen.xwd

language: node_js

node_js:
  - 0.12

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq netpbm

install:
  - npm install
  - npm install -g cypress

script:
  - http-server -p 6060 &
  - xwd -root -silent -display :99  > screen.xwd
  - cypress ci
